import React from 'react';
import {
  Dialog,
  DialogContent,
  Box,
  Typography,
  Button,
  IconButton,
  Divider,
  Chip,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
} from '@mui/material';
import {
  FileText,
  Download,
  X,
  CheckCircle,
  Pill,
  Calendar,
  Building2,
} from 'lucide-react';
import jsPDF from 'jspdf';

interface PrescriptionModalProps {
  open: boolean;
  onClose: () => void;
  data: {
    doctorName: string;
    doctorSpecialty: string;
    doctorHospital?: string;
    doctorLicense?: string;
    patientName: string;
    patientAge?: string | number;
    patientGender?: string;
    date: string;
    diagnosis: string;
    symptoms?: string[];
    vitalsSummary?: string;
    medicines: Array<{
      name: string;
      dosage: string;
      frequency: string;
      duration: string;
      instructions?: string;
    }>;
    advice: string;
    followUp?: string;
  };
}

export const PrescriptionModal: React.FC<PrescriptionModalProps> = ({
  open,
  onClose,
  data,
}) => {
  const handleDownloadPDF = () => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(16, 185, 129); // Emerald
    doc.rect(0, 0, 210, 28, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Dr.AI Medical Network - Official Prescription', 14, 18);

    // Doctor info
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(data.doctorName, 14, 38);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(data.doctorSpecialty, 14, 44);
    doc.text(data.doctorHospital || 'Telehealth Clinical Services • MediConnect AI', 14, 49);
    doc.text(`License: ${data.doctorLicense || 'MD-TELE-98234-VERIFIED'}`, 14, 54);

    doc.setDrawColor(226, 232, 240);
    doc.line(14, 58, 196, 58);

    // Patient & Date info
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.text('PATIENT DETAILS', 14, 66);
    doc.text('CONSULTATION DATE', 140, 66);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(`Name: ${data.patientName}`, 14, 72);
    doc.text(`Age/Gender: ${data.patientAge || '30'} yrs / ${data.patientGender || 'Adult'}`, 14, 77);
    doc.text(`Date: ${data.date}`, 140, 72);
    doc.text(`Rx ID: RX-${Math.floor(100000 + Math.random() * 900000)}`, 140, 77);

    doc.line(14, 83, 196, 83);

    // Diagnosis
    doc.setTextColor(16, 185, 129);
    doc.setFont('helvetica', 'bold');
    doc.text('PRIMARY CLINICAL DIAGNOSIS:', 14, 91);

    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'normal');
    doc.text(data.diagnosis, 14, 97);

    // Medicines Table
    doc.setFillColor(241, 245, 249);
    doc.rect(14, 105, 182, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text('MEDICATION', 18, 110);
    doc.text('DOSAGE', 85, 110);
    doc.text('FREQUENCY', 125, 110);
    doc.text('DURATION', 165, 110);

    let startY = 118;
    data.medicines.forEach((med, idx) => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`${idx + 1}. ${med.name}`, 18, startY);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text(med.dosage, 85, startY);
      doc.text(med.frequency, 125, startY);
      doc.text(med.duration, 165, startY);

      startY += 10;
    });

    // Clinical Advice
    startY += 4;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(16, 185, 129);
    doc.text('PHYSICIAN ADVICE & RECOMMENDATIONS:', 14, startY);

    startY += 6;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const splitAdvice = doc.splitTextToSize(data.advice, 182);
    doc.text(splitAdvice, 14, startY);

    startY += splitAdvice.length * 6 + 10;
    if (data.followUp) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`Follow-up: ${data.followUp}`, 14, startY);
      startY += 10;
    }

    // Signature stamp
    doc.setDrawColor(16, 185, 129);
    doc.rect(135, startY, 60, 24);
    doc.setFontSize(8);
    doc.setTextColor(16, 185, 129);
    doc.text('DIGITALLY SIGNED & VERIFIED', 138, startY + 6);
    doc.text(data.doctorName, 138, startY + 12);
    doc.text(new Date().toLocaleDateString(), 138, startY + 18);

    // Footer Disclaimer
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text(
      'This is an authorized electronic medical consultation summary generated by Dr.AI Telehealth Services.',
      14,
      285
    );

    doc.save(`Prescription_${data.patientName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      PaperProps={{
        sx: {
          borderRadius: 4,
          overflow: 'hidden',
          background: (theme) =>
            theme.palette.mode === 'dark' ? '#0F172A' : '#FFFFFF',
          border: '1px solid rgba(16, 185, 129, 0.25)',
        },
      }}
    >
      <Box className="bg-gradient-to-r from-emerald-600 to-teal-700 text-white p-5 flex items-center justify-between">
        <Box className="flex items-center gap-3">
          <Box className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center">
            <FileText className="w-6 h-6 text-white" />
          </Box>
          <Box>
            <Typography variant="h6" className="font-bold">
              Official Medical Prescription & Summary
            </Typography>
            <Typography variant="caption" className="text-emerald-100">
              Verified Digital Clinical Document
            </Typography>
          </Box>
        </Box>
        <Box className="flex items-center gap-2">
          <Button
            variant="contained"
            onClick={handleDownloadPDF}
            startIcon={<Download className="w-4 h-4" />}
            sx={{
              backgroundColor: 'white',
              color: '#059669',
              fontWeight: 'bold',
              '&:hover': { backgroundColor: '#F0FDF4' },
              borderRadius: 2,
            }}
          >
            Download PDF
          </Button>
          <IconButton onClick={onClose} sx={{ color: 'white' }}>
            <X className="w-5 h-5" />
          </IconButton>
        </Box>
      </Box>

      <DialogContent sx={{ p: 4 }}>
        {/* Doctor Header */}
        <Box className="flex flex-col sm:flex-row justify-between items-start pb-4 border-b border-gray-200 dark:border-gray-800 gap-4">
          <Box>
            <Typography variant="h6" className="font-bold text-gray-900 dark:text-gray-100">
              {data.doctorName}
            </Typography>
            <Typography variant="body2" className="text-emerald-600 dark:text-emerald-400 font-medium">
              {data.doctorSpecialty}
            </Typography>
            <Typography variant="caption" className="text-gray-500 dark:text-gray-400 flex items-center gap-1 mt-0.5">
              <Building2 className="w-3.5 h-3.5" /> {data.doctorHospital || 'Telehealth Network'}
            </Typography>
          </Box>
          <Box className="text-left sm:text-right">
            <Chip
              label="Verified Rx"
              icon={<CheckCircle className="w-3.5 h-3.5 text-emerald-600" />}
              size="small"
              sx={{ backgroundColor: 'rgba(16, 185, 129, 0.15)', color: '#059669', fontWeight: 600, mb: 0.5 }}
            />
            <Typography variant="caption" className="text-gray-500 dark:text-gray-400 block">
              Date: {data.date}
            </Typography>
          </Box>
        </Box>

        {/* Patient Details */}
        <Box className="grid grid-cols-2 sm:grid-cols-4 gap-4 my-4 p-3 rounded-xl bg-gray-50 dark:bg-gray-800/60 border border-gray-100 dark:border-gray-800">
          <Box>
            <Typography variant="caption" className="text-gray-400 block font-semibold uppercase">Patient Name</Typography>
            <Typography variant="body2" className="font-bold text-gray-800 dark:text-gray-200">{data.patientName}</Typography>
          </Box>
          <Box>
            <Typography variant="caption" className="text-gray-400 block font-semibold uppercase">Age / Gender</Typography>
            <Typography variant="body2" className="font-bold text-gray-800 dark:text-gray-200">{data.patientAge || '30'} yrs / {data.patientGender || 'Adult'}</Typography>
          </Box>
          <Box>
            <Typography variant="caption" className="text-gray-400 block font-semibold uppercase">Rx Number</Typography>
            <Typography variant="body2" className="font-bold text-emerald-600 dark:text-emerald-400">RX-849201</Typography>
          </Box>
          <Box>
            <Typography variant="caption" className="text-gray-400 block font-semibold uppercase">Consultation Mode</Typography>
            <Typography variant="body2" className="font-bold text-gray-800 dark:text-gray-200">Video Telehealth</Typography>
          </Box>
        </Box>

        {/* Clinical Diagnosis */}
        <Box className="mb-4">
          <Typography variant="subtitle2" className="font-bold text-emerald-600 dark:text-emerald-400 mb-1 flex items-center gap-1.5">
            <Pill className="w-4 h-4" /> Clinical Diagnosis & Impression
          </Typography>
          <Box className="p-3 rounded-lg bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/50">
            <Typography variant="body1" className="font-semibold text-gray-900 dark:text-gray-100">
              {data.diagnosis}
            </Typography>
          </Box>
        </Box>

        {/* Medicines Table */}
        <Box className="mb-4">
          <Typography variant="subtitle2" className="font-bold text-gray-900 dark:text-gray-100 mb-2">
            Prescribed Medications (Rx)
          </Typography>
          <Table size="small" className="border border-gray-200 dark:border-gray-800 rounded-lg overflow-hidden">
            <TableHead className="bg-gray-100 dark:bg-gray-800">
              <TableRow>
                <TableCell className="font-bold text-gray-700 dark:text-gray-300">Medication</TableCell>
                <TableCell className="font-bold text-gray-700 dark:text-gray-300">Dosage</TableCell>
                <TableCell className="font-bold text-gray-700 dark:text-gray-300">Frequency</TableCell>
                <TableCell className="font-bold text-gray-700 dark:text-gray-300">Duration</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {data.medicines.map((med, idx) => (
                <TableRow key={idx} className="hover:bg-gray-50 dark:hover:bg-gray-800/40">
                  <TableCell className="font-semibold text-emerald-700 dark:text-emerald-300">
                    {med.name}
                  </TableCell>
                  <TableCell className="text-gray-700 dark:text-gray-300">{med.dosage}</TableCell>
                  <TableCell className="text-gray-700 dark:text-gray-300">{med.frequency}</TableCell>
                  <TableCell className="text-gray-700 dark:text-gray-300">{med.duration}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Box>

        {/* Doctor Advice */}
        <Box className="mb-4">
          <Typography variant="subtitle2" className="font-bold text-gray-900 dark:text-gray-100 mb-1">
            Instructions & Dietary Advice
          </Typography>
          <Typography variant="body2" className="text-gray-700 dark:text-gray-300 whitespace-pre-line p-3 rounded-lg bg-gray-50 dark:bg-gray-800/40">
            {data.advice}
          </Typography>
        </Box>

        {data.followUp && (
          <Box className="flex items-center gap-2 p-3 rounded-lg bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-900 text-blue-800 dark:text-blue-200">
            <Calendar className="w-4 h-4 text-blue-600 flex-shrink-0" />
            <Typography variant="body2" className="text-sm font-medium">
              <strong>Follow-up Recommendation:</strong> {data.followUp}
            </Typography>
          </Box>
        )}

        <Divider sx={{ my: 3 }} />

        {/* Footer actions */}
        <Box className="flex justify-between items-center">
          <Typography variant="caption" className="text-gray-400">
            Signed by digital certificate: MD-CERT-{Math.floor(10000 + Math.random() * 90000)}
          </Typography>
          <Button
            variant="contained"
            onClick={handleDownloadPDF}
            startIcon={<Download className="w-4 h-4" />}
            sx={{
              background: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
              borderRadius: 2,
              px: 3,
            }}
          >
            Export as PDF
          </Button>
        </Box>
      </DialogContent>
    </Dialog>
  );
};
